// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCef7wmZxwyffeAKanIRZGlEbCqW2jCHv0',
    appId: '1:1067967328391:web:4a25a19a91fd8add448822',
    messagingSenderId: '1067967328391',
    projectId: 'digital-e7952',
    authDomain: 'digital-e7952.firebaseapp.com',
    databaseURL: 'https://digital-e7952-default-rtdb.firebaseio.com',
    storageBucket: 'digital-e7952.appspot.com',
    measurementId: 'G-DNL8L078YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8wgcal_wuBeTy2QvQ7o7cDs9Qee4DVJk',
    appId: '1:1067967328391:android:fea8d19c245969a9448822',
    messagingSenderId: '1067967328391',
    projectId: 'digital-e7952',
    databaseURL: 'https://digital-e7952-default-rtdb.firebaseio.com',
    storageBucket: 'digital-e7952.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTwciYZaanQE2T8nW3Opwz3dY5Rvr1fhs',
    appId: '1:1067967328391:ios:5de6012a5e167ffb448822',
    messagingSenderId: '1067967328391',
    projectId: 'digital-e7952',
    databaseURL: 'https://digital-e7952-default-rtdb.firebaseio.com',
    storageBucket: 'digital-e7952.appspot.com',
    iosBundleId: 'com.example.nerdspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTwciYZaanQE2T8nW3Opwz3dY5Rvr1fhs',
    appId: '1:1067967328391:ios:ad028a7043b3e3f9448822',
    messagingSenderId: '1067967328391',
    projectId: 'digital-e7952',
    databaseURL: 'https://digital-e7952-default-rtdb.firebaseio.com',
    storageBucket: 'digital-e7952.appspot.com',
    iosBundleId: 'com.example.nerdspace.RunnerTests',
  );
}
